"$schema" = 'https://starship.rs/config-schema.json'


format = """
[╭─](fg:surface2)\
[](fg:surface1)\
$os\
$python\
$hostname\
[](bg:peach fg:surface1)\
$directory\
[](bg:yellow fg:peach)\
$git_branch\
$git_status\
[](fg:yellow bg:green)\
$c$rust$golang$nodejs$php$java$kotlin$haskell$python\
[](fg:green bg:sapphire)\
$conda\
[](fg:sapphire bg:lavender)\
[](fg:lavender)\
$line_break\
[╰─](fg:surface2)\
$character"""

right_format = """
$time()\

[](fg:surface1)\
$username\
[](fg:surface1)\

"""

palette = 'catppuccin_mocha'

add_newline = true

[line_break]
disabled = false

# Disable the blank line at the start of the prompt
# add_newline = false

scan_timeout = 1000


# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[custom.arch]
command = "echo -n "  # Unicode icon; try ⎈ if your font doesn't support Nerd Fonts
style = "bold purple"
when = "true"  # Always show


[hostname]
ssh_only = false
format = "[$hostname]($style)"
trim_at = "-"
#style = "fg:#D43BC0"
disabled = false
style = "bg:surface1 fg:text"

#[hostname]
#ssh_only = false
#format = "[$hostname]($style)"
#disabled = false
#style = "bg:#52085f fg:#FFFFFF"

[username]
show_always = true
style_user = "bg:surface1 fg:text"
#style_user = "bg:transparent fg:#D1C932"
#style_root = "bg:#52085f"

format = '[ $user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
#style = "fg:#ffffff bg:#3B4252"
#style = "fg:#ffffff"
style = "bg:surface1 fg:text"
disabled = false # Disabled by default

[directory]
style = "bg:peach fg:crust"
format = "[ $path ]($style)"
truncation_length = 0

[directory.substitutions]
"~" = " "

[git_branch]
symbol = " "
style = "bg:yellow fg:crust"
format = '[ $symbol$branch ]($style)'

[git_status]
style = "bg:yellow fg:crust"
format = '[($all_status$ahead_behind )]($style)'

[nodejs]
symbol = " "
style = "bg:green"
format = '[[ $symbol](fg:crust bg:green)]($style)'

[c]
symbol = " "
style = "bg:green"
format = '[[ $symbol](fg:crust bg:green)]($style)'

[rust]
symbol = " "
style = "bg:green"
format = '[[ $symbol](fg:crust bg:green)]($style)'

[golang]
symbol = "󰟓 "
style = "bg:green"
format = '[[ $symbol](fg:crust bg:green)]($style)'

[php]
symbol = " "
style = "bg:green"
format = '[[ $symbol](fg:crust bg:green)]($style)'

[java]
symbol = " "
style = "bg:green"
format = '[[ $symbol](fg:crust bg:green)]($style)'

[kotlin]
symbol = " "
style = "bg:green"
format = '[[ $symbol](fg:crust bg:green)]($style)'

[haskell]
symbol = " "
style = "bg:green"
format = '[[ $symbol](fg:crust bg:green)]($style)'

[python]
symbol = " "
style = "bg:green"
format = '[[ $symbol( $version)(\(#$virtualenv\)) ](fg:crust bg:green)]($style)'

[conda]
symbol = " "
style = "bg:sapphire"
format = '[[ $symbol( $environment) ](fg:crust bg:sapphire)]($style)'


[time]
disabled = false
time_format = "%r" # Hour:Minute Format
style = "bg:transparent fg:yellow"
format = '[  $time ]($style)'


[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[palettes.catppuccin_mocha]
red = "#ff5f5f"
peach = "#ed8796"
yellow = "#eed49f"
green = "#a6da95"
sapphire = "#7dc4e4"
lavender = "#b4befe"
crust = "#11111b"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
text = "#1793d1"
