-- Generated by nwg-displays on 2026-08-14 at 01:59:28. Do not edit manually.

hl.monitor({
    output = "DP-1",
    mode = "1920x1080@165.0",
    position = "0x762",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "3840x2160@60.0",
    position = "3200x762",
    scale = 1.0
})
hl.monitor({
    output = "DP-2",
    mode = "1920x1080@60.0",
    position = "1920x762",
    scale = 1.5
})
hl.monitor({
    output = "HDMI-A-2",
    mode = "1024x600@75.8",
    position = "0x1842",
    scale = 1
})
