-- Generated by nwg-displays on 2026-07-20 at 23:32:44. Do not edit manually.

hl.monitor({
    output = "DP-1",
    mode = "1920x1080@165.0",
    position = "0x0",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60.0",
    position = "1920x0",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-2",
    mode = "1024x600@75.8",
    position = "0x1080",
    scale = 1.0
})
